### ISSUE TITLE
Can't select a COM Port in Windows

### ISSUE THREAD

**Issue by Ed1954** [emsesp/EMS-ESP-Flasher#11]
The system does not recognize the selection for com4.

![Unbenannt](https://github.com/emsesp/EMS-ESP-Flasher/assets/72298677/b2cca747-0d84-405d-9fb6-e9829d0323a6)

**Comment by proddy** [comment]
Thanks for reporting. We'll investigate

**Comment by proddy** [comment]
I made a fix, but away from home and ESPs for a while so can't test !

**Comment by Ed1954** [comment]
Any chance to get the windows exe so i can do the tests for you ?

**Comment by proddy** [comment]
try https://github.com/emsesp/EMS-ESP-Flasher/actions/runs/9572857376

watch ouf for the Flag to keep the settings otherwise the Flash will be erased

**Comment by Ed1954** [comment]
Just testet and run into an error.

![Flasher_1_0_4](https://github.com/emsesp/EMS-ESP-Flasher/assets/72298677/778bd2e8-15b2-4b9d-80eb-b2022fba329b)

BTW Microsoft Antivirus detected a "Virus"

**Comment by proddy** [comment]
Ok, I'll take a look. I probably need to wait until I get home to try out with a real USB and ESP32. The virus warning on Windows is a known issue (Tasmota has it too). I'll make a note of it.

**Comment by Ed1954** [comment]
OK.  don`t hurry. Meanwhile i ordered a new  EMS-ESP Device from BBKees to keep my System online.

**Comment by proddy** [comment]
maybe https://github.com/emsesp/EMS-ESP-Flasher/actions/runs/9584349634 is better

I'm shooting in the dark as I can't test

**Comment by Ed1954** [comment]
Thanks for your help, but

![Flasher_1_0_4](https://github.com/emsesp/EMS-ESP-Flasher/assets/72298677/90b60c0e-f329-4673-966e-406011f34760)

**Comment by proddy** [comment]
I couldn't get the latest version based on Qt working well, so rolled everything back to 1.0.3

**Comment by Ed1954** [comment]
Thanks for your help. Version 1.0.3 did the job.

**Comment by proddy** [comment]
thanks, the option to erase the flash has gone, but we can add that back later
