### ISSUE TITLE
Rename the zip files

### ISSUE THREAD

**Issue by bbqkees** [emsesp/EMS-ESP-Flasher#13]
Some virus scanners or anti-malware software will flag the 'Windows.zip' file as suspicious.
I think if it is renamed 'EMS-ESP Flash tool for Window.zip' or similar this will cause less issues.

**Comment by proddy** [comment]
Agree

it should not create zips but 
 `EMS-ESP-Flasher.exe` for Windows
 `macOS.tar`
 `Ubuntu.tar`
 
to make it more specific.

**Comment by bbqkees** [comment]
The short name with 'Windows.zip' will be flagged as suspicious.
If the extension is .exe it will probably also be blocked by the same anti-malware software.
So the .zip is a good workaround for downloading the exe file, but then we have to make the zip file name different. 
For the Linux and Mac version it probably does not matter that much if it is a direct .tar/gz file instead of the .zip.

(Now I think if it it as you mentioned putting a compressed .gz file in a .zip is superfluous anyway.)

**Comment by proddy** [comment]
fixed in v1.1.0 - https://github.com/emsesp/EMS-ESP-Flasher/releases/tag/v1.1.0
