### ISSUE TITLE
bootloader_dio_40m.bin not found

### ISSUE THREAD

**Issue by ekivel** [emsesp/EMS-ESP-Flasher#17]
Hi,
using flasher tool, getting this error:
Unexpected error: Error while retrieving firmware file 'https://github.com/espressif/arduino-esp32/raw/2.0.5/tools/sdk/loader/bin/bootloader_dio_40m.bin': 404 Client Error: Not Found for url: https://github.com/espressif/arduino-esp32/raw/2.0.5/tools/sdk/loader/bin/bootloader_dio_40m.bin

Thanks

**Comment by Drawer** [comment]
Had the same issue. 1.0.3 release does not have the issue.

**Comment by proddy** [comment]
Latest version of the flasher is 1.1.0 - do you get the same error with this?

**Comment by Drawer** [comment]
> Latest version of the flasher is 1.1.0 - do you get the same error with this?

Sorry if my reply wasn't clear. I have the issue with 1.1.0 as well, but not with 1.0.3 is what I was trying to say.

**Comment by proddy** [comment]
Ah I see the problem. The flash tool thinks you're installing the 'loader' which is a special boot loader version of the firmware. I'll make a change in the Flash code. 

Out of interest can you post details of the .bin file you're trying to install (name + size) ?

**Comment by Drawer** [comment]
> Ah I see the problem. The flash tool thinks you're installing the 'loader' which is a special boot loader version of the firmware. I'll make a change in the Flash code.
> 
> Out of interest can you post details of the .bin file you're trying to install (name + size) ?

In my scenario, but I'm not the original issue maker, I was trying to use https://github.com/emsesp/EMS-ESP32/releases/download/v3.6.5/EMS-ESP-3_6_5-ESP32-16MB+.bin, freshly downloaded.

**Comment by proddy** [comment]
and which ESP32 board do you use, because the Flasher thinks its 4MB but you're downloading a 16MB bin file

**Comment by proddy** [comment]
@bbqkees any ideas?

**Comment by Drawer** [comment]
> and which ESP32 board do you use, because the Flasher thinks its 4MB but you're downloading a 16MB bin file

I'm using a (I know, not supported, but it works) ESP32-WROOM-32, which indeed seems to be a 4MB device, looking at the system status:
![image](https://github.com/user-attachments/assets/657b8607-105e-4846-9d11-497721b112ba)

**Comment by proddy** [comment]
ok. I'll need to find an ESP32 with 4MB and test it, and then make a fix. I never tried this combination.

**Comment by bbqkees** [comment]
They probably changed the location of that bin file in the /espressif/arduino-esp32/ repository.
Had a quick look but I could not find it where it is now (if still existing).

**Comment by Drawer** [comment]
> They probably changed the location of that bin file in the /espressif/arduino-esp32/ repository. Had a quick look but I could not find it where it is now (if still existing).

https://github.com/espressif/arduino-esp32/tree/2.0.5/tools/sdk/esp32/bin
I think here? But it's now seperated per ESP-version as well. 
![image](https://github.com/user-attachments/assets/049e94f2-61e3-44ce-8806-87cf29fc445e)

**Comment by proddy** [comment]
it was in the code, fixed now and new installer is building. Because the board was 4MB Flash and a smaller bin size we had assumed it was a bootloader, which is why the word 'loader' sneaked itself into the URL. I found an older S32 with 4MB and tested it, so it works now. Grab the new .exe in a few minutes from https://github.com/emsesp/EMS-ESP-Flasher/releases/tag/v1.1.0

Thanks for reporting this!

**Comment by ekivel** [comment]
it works now... thanks
