### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.

### ISSUE THREAD

**Issue by red-black-bonsai** [emsesp/EMS-ESP-Flasher#19]
I'm having issues running the flasher on Ubuntu 22.04.5 LTS with xfce:

	./EMS-ESP-Flasher 
	Failed to create wl_display (No such file or directory)
	qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
	This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

	Available platform plugins are: linuxfb, offscreen, minimal, wayland, xcb, minimalegl, vkkhrdisplay, vnc, wayland-egl.

	Aborted

Any hints on what I'm missing? I tried installing a bunch of wayland packages but still no luck.

	dpkg -l | grep -i wayland
	ii  libqt5waylandclient5:amd64                                  5.15.3-1                                amd64        QtWayland client library
	ii  libqt5waylandclient5-dev:amd64                              5.15.3-1                                amd64        QtWayland client development files
	ii  libqt5waylandcompositor5:amd64                              5.15.3-1                                amd64        QtWayland compositor library
	ii  libqt6waylandclient6:amd64                                  6.2.4-1                                 amd64        Qt 6 Wayland Client library
	ii  libqt6waylandcompositor6:amd64                              6.2.4-1                                 amd64        Qt 6 Wayland Compositor library
	ii  libqt6waylandeglclienthwintegration6:amd64                  6.2.4-1                                 amd64        Qt 6 Wayland WaylandEglClientHwIntegration library
	ii  libqt6waylandeglcompositorhwintegration6:amd64              6.2.4-1                                 amd64        Qt 6 Wayland WaylandEglCompositorHwIntegration library
	ii  libqt6wlshellintegration6:amd64                             6.2.4-1                                 amd64        Qt 6 Wayland ShellIntegration library
	ii  libwayland-bin                                              1.20.0-1ubuntu0.1                       amd64        wayland compositor infrastructure - binary utilities
	ii  libwayland-client0:amd64                                    1.20.0-1ubuntu0.1                       amd64        wayland compositor infrastructure - client library
	ii  libwayland-cursor0:amd64                                    1.20.0-1ubuntu0.1                       amd64        wayland compositor infrastructure - cursor library
	ii  libwayland-dev:amd64                                        1.20.0-1ubuntu0.1                       amd64        wayland compositor infrastructure - development files
	ii  libwayland-egl1:amd64                                       1.20.0-1ubuntu0.1                       amd64        wayland compositor infrastructure - EGL library
	ii  libwayland-server0:amd64                                    1.20.0-1ubuntu0.1                       amd64        wayland compositor infrastructure - server library
	ii  qt6-wayland:amd64                                           6.2.4-1                                 amd64        Qt 6 Wayland platform plugin
	ii  qt6-wayland-dev:amd64                                       6.2.4-1                                 amd64        Qt 6 Wayland - development files
	ii  qt6-wayland-dev-tools                                       6.2.4-1                                 amd64        Qt 6 Wayland developer tools
	ii  qtwayland5:amd64                                            5.15.3-1                                amd64        QtWayland platform plugin
	ii  qtwayland5-dev-tools                                        5.15.3-1                                amd64        Qt 5 Wayland developer tools
	ii  wayland-protocols                                           1.25-1                                  all          wayland compositor protocols

**Comment by proddy** [comment]
no idea, sorry. I never tested it on Linux as I was only using WSL without the X11 libraries. Could you try forking the code and building/running directly to see if that works? `python -m emsesp_flasher`

**Comment by red-black-bonsai** [comment]
OK, so what still works for me is:

- Going back to commit 824b2a0
- Using conda to install python 3.7 and wxpython, install, build and then run esp_flasher:

		conda create -n emsflasher python=3.7 wxpython -y
		conda activate emsflasher
		pip install --upgrade build
		pip install --no-cache-dir -e .
		python esp_flasher

What I also just tried:

	git clone https://github.com/emsesp/EMS-ESP-Flasher.git
	sudo apt install python3.10-venv
	python3 -m venv venv
	source ./venv/bin/activate
	pip install --upgrade build
	pip install -e .
	python -m emsesp_flasher

Result:

	Failed to create wl_display (No such file or directory)
	qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
	This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

	Available platform plugins are: eglfs, xcb, offscreen, vnc, wayland, minimalegl, linuxfb, wayland-egl, minimal, vkkhrdisplay.

	Aborted

**Comment by proddy** [comment]
I don't want to go back to wxpython, I'll find a way. I'm back home later this week and then can try on a native Ubuntu. The code is based on Tasmota. Does https://github.com/Jason2866/ESP_Flasher/releases/download/v3.0.3/Ubuntu.tar work for you?

**Comment by red-black-bonsai** [comment]
Sadly, no, same issue

	./ESP-Flasher 
	Failed to create wl_display (No such file or directory)
	qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
	This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

	Available platform plugins are: linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

	Aborted

**Comment by proddy** [comment]
I tested with Ubuntu under WSL2 and the only fix I could find online is to disable systemd in `/etc/wsl.conf` which is silly. After that running `python -m emsesp_flasher` worked.  I don't know how to fix this on Native Ubuntu. If you want to flash EMS-ESP to the latest version you could always use install.emsesp.org. I'll keep looking...

**EDIT**

I just upgraded to Ubuntu 24.10/oracular and it works on my setup without hacking the systems.

**Comment by red-black-bonsai** [comment]
Sorry for answering so late...

Good to know that with Ubuntu 24 the issue should go away (haven't updated just yet) :)
Re install.emsesp.org: I'm a firefox user, so I had hoped the flasher would be my workaround.

Since the ESP flasher docs mention that it uses esptool under the hood: is the esptool command for flashing EMS ESP overly complicated? Could I just use that as a workaround?

**Comment by proddy** [comment]
sure, I'll create a new project with the scripts for you now

**Comment by proddy** [comment]
@red-black-bonsai you can use https://github.com/emsesp/EMS-ESP-Flasher-CLI

Fork it, run firmware.sh and then run upload.sh - the rest is magic

**Comment by red-black-bonsai** [comment]
Wow, that looks *awesome*! Thanks a lot! I need to delve into that now :smiley:

**Comment by olivluca** [comment]
The problem is that emsesp_flasher/guy.py forces the `QT_QPA_PLATFORM` environment variable to `wayland` for ubuntu and debian. In my case (debian 12) I prefer to run plasma with x11 instead of wayland, so I get the error. With this modification I can successfully run the flasher:

```
diff --git a/emsesp_flasher/gui.py b/emsesp_flasher/gui.py
index b083d53..88430db 100644
--- a/emsesp_flasher/gui.py
+++ b/emsesp_flasher/gui.py
@@ -203,7 +203,7 @@ def main():
     elif os_name == 'Linux':
         distro_name = distro.id().lower()
         if 'ubuntu' in distro_name or 'debian' in distro_name:
-            os.environ['QT_QPA_PLATFORM'] = 'wayland'
+            pass
         else:
             os.environ['QT_QPA_PLATFORM'] = 'xcb'
     elif os_name == 'Windows':
```

I'm not sure it's a good idea to force that variable, at least for debian.

**Comment by proddy** [comment]
thanks, I'll see if it still builds and runs on Ubuntu with this removed.
